package roadmonitor;

/**
 *
 * @author Nikolas Misins
 */
public class RoadMonitorGUI extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoadMonitorGUI.class.getName());

    PriorityQueue issueList;
    Stack historyList;
    
    /**
     * Creates new form RoadMonitorGUI
     */
    public RoadMonitorGUI() {
        initComponents();
        issueList = new PriorityQueue();
        historyList = new Stack();
        
        loadDemoData();
        viewTrafficMode();

        
    }
    
    //misc methods

    /**
     * sets the GUI to let the user see issues affecting traffic
     */
    public void viewTrafficMode(){
        weatherWarningBTN.setVisible(false);
        emergencyBTN.setVisible(false);
        constructionBTN.setVisible(false);
        eventBTN.setVisible(false);
        miscBTN.setVisible(false);
        eventDescTF.setVisible(false);
        addBTN.setVisible(false);
        EventTypeLBL.setVisible(false);
        
        statusLBL.setVisible(true);
        statusIndicatorTF.setVisible(true);
        displayTA.setText("Current traffic events in Docklands:\n\n");
        
        updateView();
    }
    
    /**
     * sets GUI to let user make/delete issues affecting traffic and history
     */
    public void editIssuesMode(){
        weatherWarningBTN.setVisible(true);
        emergencyBTN.setVisible(true);
        constructionBTN.setVisible(true);
        eventBTN.setVisible(true);
        miscBTN.setVisible(true);
        eventDescTF.setVisible(true);
        addBTN.setVisible(true);
        EventTypeLBL.setVisible(true);
        
        statusLBL.setVisible(false);
        statusIndicatorTF.setVisible(false);
        displayTA.setText("Most Recent traffic event that has ended:\n\n");
        
        updateView();
    }
    
    /**
     * For adding a current issue to the priority queue
     */
    public void logIssue(){
        int priorityKey;
        
        if(weatherWarningBTN.isSelected()){
            priorityKey=1;
        }
        else if(emergencyBTN.isSelected()){
            priorityKey=2;
        }  
        else if(constructionBTN.isSelected()){
            priorityKey=4;
        }
        else if(eventBTN.isSelected()){
            priorityKey=3;
        }
        else{
            priorityKey=5;
        }
        
        Issue newIssue = new Issue(eventDescTF.getText(),priorityKey);
        
        issueList.enqueue(newIssue);
    }
    
    /**
     * dequeue the top current traffic issue
     */
    public void dequeueIssue(){
        //issueList.peek() returns top
        //put that into stack
        historyList.push(issueList.peek());
        //dequeue theList
        issueList.dequeue();
    }
    
    /**
     * Fabricates some existing data into the ADTs for the purpose of testing and showing that it works quickly. Better
     * than hardcoding the data into the ADTs obviously.
     * In a real world scenario, this would be loading data from a file or database.
     */
    public void loadDemoData(){
        Issue i = new Issue("Orange Flood Weather Warning for the Dublin Area",1);
        issueList.enqueue(i);
        
        Issue p = new Issue("Saint Patrick's day parade",3);
        historyList.push(p);
    }
    
    /**
     * TO be called after any kind of change to ADTs so that the user has up-to-date data on the dashboard.
     */
    public void updateView(){
        if (ViewIssuesBTN.isSelected()){
            displayTA.append(issueList.printList());
        }else{
            String toShow = historyList.peek().getDescription() + ", it had a priority impact level of " + historyList.peek().getPriority();
            displayTA.append(toShow);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EventType = new javax.swing.ButtonGroup();
        formType = new javax.swing.ButtonGroup();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        statusLBL = new javax.swing.JLabel();
        weatherWarningBTN = new javax.swing.JRadioButton();
        eventBTN = new javax.swing.JRadioButton();
        constructionBTN = new javax.swing.JRadioButton();
        emergencyBTN = new javax.swing.JRadioButton();
        ViewIssuesBTN = new javax.swing.JRadioButton();
        LogIssuesBTN = new javax.swing.JRadioButton();
        statusIndicatorTF = new javax.swing.JTextField();
        miscBTN = new javax.swing.JRadioButton();
        addBTN = new javax.swing.JButton();
        eventDescTF = new javax.swing.JTextField();
        EventTypeLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setSize(new java.awt.Dimension(100, 500));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("RoadMonitor");

        displayTA.setEditable(false);
        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        statusLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        statusLBL.setText("Dockland Status:");

        EventType.add(weatherWarningBTN);
        weatherWarningBTN.setSelected(true);
        weatherWarningBTN.setText("Weather Warning");
        weatherWarningBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weatherWarningBTNActionPerformed(evt);
            }
        });

        EventType.add(eventBTN);
        eventBTN.setText("event (eg. parade)");

        EventType.add(constructionBTN);
        constructionBTN.setText("construction");
        constructionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constructionBTNActionPerformed(evt);
            }
        });

        EventType.add(emergencyBTN);
        emergencyBTN.setText("emergency");

        formType.add(ViewIssuesBTN);
        ViewIssuesBTN.setSelected(true);
        ViewIssuesBTN.setText("View Current Traffic");
        ViewIssuesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewIssuesBTNActionPerformed(evt);
            }
        });

        formType.add(LogIssuesBTN);
        LogIssuesBTN.setText("Log/Delete Traffic");
        LogIssuesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIssuesBTNActionPerformed(evt);
            }
        });

        statusIndicatorTF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        statusIndicatorTF.setText("...");
        statusIndicatorTF.setFocusable(false);

        EventType.add(miscBTN);
        miscBTN.setText("other");
        miscBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miscBTNActionPerformed(evt);
            }
        });

        addBTN.setText("log event");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        eventDescTF.setBackground(new java.awt.Color(204, 204, 204));
        eventDescTF.setForeground(new java.awt.Color(0, 0, 0));
        eventDescTF.setText("Describe Traffic Event here");
        eventDescTF.setAutoscrolls(false);
        eventDescTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eventDescTFMouseReleased(evt);
            }
        });
        eventDescTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventDescTFActionPerformed(evt);
            }
        });

        EventTypeLBL.setText("Event Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusLBL)
                        .addGap(18, 18, 18)
                        .addComponent(statusIndicatorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LogIssuesBTN)
                                        .addGap(22, 22, 22))
                                    .addComponent(ViewIssuesBTN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EventTypeLBL)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(constructionBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emergencyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(eventBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(miscBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(weatherWarningBTN)
                                                .addGap(4, 4, 4))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBTN)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eventDescTF, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLBL)
                    .addComponent(statusIndicatorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(eventDescTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBTN)
                        .addGap(44, 44, 44)
                        .addComponent(EventTypeLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weatherWarningBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emergencyBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(constructionBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(miscBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewIssuesBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogIssuesBTN)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weatherWarningBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weatherWarningBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weatherWarningBTNActionPerformed

    private void ViewIssuesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewIssuesBTNActionPerformed
        viewTrafficMode();
    }//GEN-LAST:event_ViewIssuesBTNActionPerformed

    private void LogIssuesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIssuesBTNActionPerformed
        editIssuesMode();
    }//GEN-LAST:event_LogIssuesBTNActionPerformed

    private void constructionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constructionBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_constructionBTNActionPerformed

    private void miscBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miscBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miscBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        logIssue();
    }//GEN-LAST:event_addBTNActionPerformed

    private void eventDescTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventDescTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventDescTFActionPerformed

    private void eventDescTFMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDescTFMouseReleased
        eventDescTF.setText("");
    }//GEN-LAST:event_eventDescTFMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RoadMonitorGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup EventType;
    private javax.swing.JLabel EventTypeLBL;
    private javax.swing.JRadioButton LogIssuesBTN;
    private javax.swing.JLabel Title;
    private javax.swing.JRadioButton ViewIssuesBTN;
    private javax.swing.JButton addBTN;
    private javax.swing.JRadioButton constructionBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JRadioButton emergencyBTN;
    private javax.swing.JRadioButton eventBTN;
    private javax.swing.JTextField eventDescTF;
    private javax.swing.ButtonGroup formType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton miscBTN;
    private javax.swing.JTextField statusIndicatorTF;
    private javax.swing.JLabel statusLBL;
    private javax.swing.JRadioButton weatherWarningBTN;
    // End of variables declaration//GEN-END:variables
}
